/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreviewsDomainSlugExampleIdRouteImport } from './routes/previews/$domain/$slug/$exampleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewsDomainSlugExampleIdRoute =
  PreviewsDomainSlugExampleIdRouteImport.update({
    id: '/previews/$domain/$slug/$exampleId',
    path: '/previews/$domain/$slug/$exampleId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/previews/$domain/$slug/$exampleId': typeof PreviewsDomainSlugExampleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/previews/$domain/$slug/$exampleId': typeof PreviewsDomainSlugExampleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/previews/$domain/$slug/$exampleId': typeof PreviewsDomainSlugExampleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/previews/$domain/$slug/$exampleId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/previews/$domain/$slug/$exampleId'
  id: '__root__' | '/' | '/previews/$domain/$slug/$exampleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PreviewsDomainSlugExampleIdRoute: typeof PreviewsDomainSlugExampleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/previews/$domain/$slug/$exampleId': {
      id: '/previews/$domain/$slug/$exampleId'
      path: '/previews/$domain/$slug/$exampleId'
      fullPath: '/previews/$domain/$slug/$exampleId'
      preLoaderRoute: typeof PreviewsDomainSlugExampleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PreviewsDomainSlugExampleIdRoute: PreviewsDomainSlugExampleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
